name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u athphane --password-stdin

      - name: Build the Docker image
        run: docker build . --tag ghcr.io/athphane/ntfy-commander:latest

      - name: Push image to ghcr.io
        run: docker push ghcr.io/athphane/ntfy-commander:latest
     